### ISSUE TITLE
[Request] Publish to Chrome Extension store

### ISSUE THREAD

**Issue by tthvo** [nganphan123/NotionYourJob#1]
## Description

@nganphan123

This is a pretty neat tool. Is this available on Chrome store? I don't really want to build the extension myself.

**Comment by nganphan123** [comment]
Stay tuned! It'll be published to Chrome soon.

**Comment by tthvo** [comment]
Looks like it's online now on [Chrome Store](https://chromewebstore.google.com/detail/notion-your-job/kidlkkpdnkmdjoapmokjnipojbfhjcgf). Thanks @nganphan123!
